### ISSUE TITLE
@extend fails

### ISSUE THREAD

**Issue by ghost** [smartgravity/grav-skeleton-bones-site#6]
Out of the box this happens using Codekit 2.6.1.
Tried several @extends in _custom.css and get this error

ul {
    @extend .no-bullet;
}

Error: "ul" failed to @extend ".no-bullet".
       The selector ".no-bullet" was not found.

Same with 

form-input-wrapper  {
    @extend  .medium-6;
}

**Comment by benblee** [comment]
In order to create the easy toggles for the Admin interface to turn CSS on and off, I've split up the full Foundation compiling file into the separate ones. 

I think this is preventing the `@extend` SASS feature because those styles aren't loaded in your custom.css file. If Foundation is compiled in it's entirety, it should work.

I've been brainstorming about an option to use the full Foundation compile file or to keep things split up. Not sure if I should include a separate file pack that can be changed out to use it this way, or keep it with all the toggle options.

If you add all imports to one file and then just load that one file for your site CSS, you can use all SASS features:

```
@charset 'utf-8';

@import 'settings';
@import 'foundation';
@import 'motion-ui';

@include foundation-global-styles;
@include foundation-grid;
@include foundation-typography;
@include foundation-button;
@include foundation-forms;
@include foundation-visibility-classes;
@include foundation-float-classes;
@include foundation-accordion;
@include foundation-accordion-menu;
@include foundation-badge;
@include foundation-breadcrumbs;
@include foundation-button-group;
@include foundation-callout;
@include foundation-close-button;
@include foundation-drilldown-menu;
@include foundation-dropdown;
@include foundation-dropdown-menu;
@include foundation-flex-video;
@include foundation-label;
@include foundation-media-object;
@include foundation-menu;
@include foundation-off-canvas;
@include foundation-orbit;
@include foundation-pagination;
@include foundation-progress-bar;
@include foundation-slider;
@include foundation-sticky;
@include foundation-reveal;
@include foundation-switch;
@include foundation-table;
@include foundation-tabs;
@include foundation-thumbnail;
@include foundation-title-bar;
@include foundation-tooltip;
@include foundation-top-bar;

@include motion-ui-transitions;
@include motion-ui-animations;

@import 'bones/overrides';
@import 'bones/bones';
@import 'bones/colors';

@import 'custom/custom';
```

**Comment by ghost** [comment]
Thank you

**Comment by benblee** [comment]
I put together a zip pack that you can download to remove all the CSS individual options and just compile everything in a single `bones.scss` file.

Don't overwrite your custom.scss file when you copy the files over, but once you change these out, things should work for better for you.

https://github.com/smartgravity/grav-theme-bones/releases/tag/v0.3.1

The download is in the comments of this release. I'll try to do this regularly if I can't figure out a better solution. It is nice to be able to use the full power of SCSS.

I really appreciate the feedback!

**Comment by ghost** [comment]
Thanks! Will try soon. One more thing, why not change the name to something more recognizable as being based on Foundation? That's what I would look for. I understand the symbolic of Bones, but a skull will not attract many people imho. While the combo Grav Foundation is the best you can get I think. Just my 2c. Anyway I appreciate your work very much.

**Comment by benblee** [comment]
Thanks for the input. I'll think it over.

I started this as a "one off" idea to see if I could get it to work, but got hooked on it and decided to make it bigger. Guess I should have thought more on the name.

Oh, and just saw the announcement that Foundation 6.1.2 was released today, so I'll be working on upgrading to it very soon.
